#' Single Cell RNA Seq Analysis Data
#'
#' A Single Cell RNAseq experiment conducted by 10X Genomics on peripheral blood mononuclear cells,
#' generated by the CellRanger pipeline.
#'
#' @source 10X Genomics, California, USA
#'
#' @format A Seurat Object (involves many different data that are relevant to the scrna seq workflow but only
#' the few depicted below are relevant to this pacakge):
#' \describe{
#'  \item{features}{The number of genes that were expressed by the cells.}
#'  \item{samples}{The number of cells involved in this experiment.}
#'  \item{seurat_clusters}{Identification of clusters for each cell.}
#'  \item{RNA}{Includes the raw and lognormalized gene expression matrices.}
#' }
"PBMC"
