#' Single Cell RNA Seq Analysis Data
#'
#' A Single Cell RNAseq experiment conducted by 10X Genomics, generated by the CellRanger pipeline.
#'
#' @source 10X Genomics
#'
#' @format A matrix with columns:
#' \describe{
#'  \item{Condition.1}{First condition, under which least light was provided
#'    to plants.}
#'  \item{Condition.2}{Second condition, under which most light was provided to plants.}
#'  \item{Condition.3}{Third condition, the control.}
#' }
#' @examples
#' \dontrun{
#'  PBMC
#' }
"PBMC"
