#' Calculate the optimum dimensionality from an elbow plot.
#'
#' A function that calculates the optimum dimensionality from an elbow plot. Involves calculating
#' slopes of the lines that begin from each point to the last point. The optimum dimensionality will
#' be determined as the point at which slopes no longer change or no visible change occurs to the slopes
#' thereafter. The plot data must be plotted by dims (x-axis) and stdev (y-axis).
#'
#' @param plot An elbow plot data used for detemining dimensionality, generated by calling ElbowPlot() on a Seurat object.
#'
#' @return This function returns an integer that represents the number of dimensionality calculated.
#'
#' @export
determine_dimensionality <- function(plot_data) {

  dimensions <- plot_data$dims
  total_dims <- length(dimensions)
  stdev <- plot_data$stdev
  slopes_so_far <- c()
  last_dim <- length(dimensions)

  for (dim in 2:last_dim) {
    slopes_so_far <- c(slopes_so_far, (stdev[dim] - stdev[dim - 1]))
  }

  dimensionality <- 1
  nth_point <- 2
  for (slope in slopes_so_far) {
    if (slope > 10 * max(slopes_so_far) && stdev[nth_point] < min(stdev) + ((max(stdev) - min(stdev)) * 0.05)) {
      print(slope)
      dimensionality <- nth_point
      return(dimensionality - 1)
    }
    nth_point <- nth_point + 1
  }

  return(dimensionality)
}

x <- determine_dimensionality(a$data)


#' Calculate the optimum dimensionality from an elbow plot.
#'
#' A function that calculates the optimum dimensionality from an elbow plot. Involves calculating
#' slopes of the lines that begin from each point to the last point. The optimum dimensionality will
#' be determined as the point at which slopes no longer change or no visible change occurs to the slopes
#' thereafter. The plot data must be plotted by dims (x-axis) and stdev (y-axis).
#'
#' @param plot An elbow plot data used for detemining dimensionality, generated by calling ElbowPlot() on a Seurat object.
#'
#' @return This function returns an integer that represents the number of dimensionality calculated.
#'
#' @export
